version: "3.8"

services:
  #  COMMENT FRONTEND AND BACKEND FOR LOCAL DEVELOPMENT!
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    environment:
      - VITE_BACKEND_LINK
    ports:
      - "4173:4173"
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - PORT
      - NODE_ENV
      - REDIS_URL
      - DATABASE_URL
    ports:
      - "3000:3000"
    restart: always
    networks:
      - communication-network
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - communication-network

  redis-container:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - communication-network

volumes:
  postgres_data:

networks:
  communication-network:
    driver: bridge
