version: "3.8"

services:
  # #  COMMENT FRONTEND AND BACKEND FOR LOCAL DEVELOPMENT!
  # frontend:
  #   build:
  #     context: .
  #     dockerfile: frontend/Dockerfile
  #     args:
  #       - VITE_BACKEND_LINK
  #   ports:
  #     - "4173:4173"
  #   depends_on:
  #     - backend
  #   restart: always

  # backend:
  #   build:
  #     context: .
  #     dockerfile: backend/Dockerfile
  #     args:
  #       DATABASE_URL: ${DATABASE_URL}
  #       PORT: ${PORT}
  #       NODE_ENV: ${NODE_ENV}
  #       REDIS_URL: ${REDIS_URL}
  #   ports:
  #     - "3000:3000"
  #   restart: always
  #   networks:
  #     - communication-network
  #   depends_on:
  #     - postgres

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - "5432:5432"
    volumes:
      - ./dockerData/postgres_data:/var/lib/postgresql/data
    networks:
      - communication-network

  redis-container:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - communication-network

volumes:
  postgres_data:

networks:
  communication-network:
    driver: bridge
